[Relocation] Fix: dust app relocation: create projects for dust apps (#11545)
Description
---
Fixes issue described in [this
thread](https://dust4ai.slack.com/archives/C08GJ7PTW3E/p1742592866471579?thread_ts=1742578164.569179&cid=C08GJ7PTW3E)

```
Some(db error: ERROR: insert or update on table "datasets" violates foreign key constraint "datasets_project_fkey"
DETAIL: Key (project)=(32599) is not present in table "projects".

Caused by:
    ERROR: insert or update on table "datasets" violates foreign key constraint "datasets_project_fkey"
    DETAIL: Key (project)=(32599) is not present in table "projects".)
````

Dust apps need projects to be created in destination core before they
can be migrated.

Then, corresponding front project ids must be updated.

This is done in activity, to avoid having to restart ongoing
relocations.

Risks
---
Relocation issues. Require careful review

Deploy
---
front